<?php
function load_blog_posts($xml_file_path, $limit = null) {
    $xml = simplexml_load_file($xml_file_path);
    $posts = [];

    foreach ($xml->channel->item as $item) {
        $title = (string) $item->title;
        $dateRaw = (string) $item->pubDate;
        $date = date('F j, Y', strtotime($dateRaw));
        $content = (string) $item->children('content', true)->encoded;

        // Skip irrelevant or autogenerated posts
        if (
            trim($content) === '' ||
            stripos($title, 'custom styles') !== false ||
            stripos($title, 'jetpack t-shirt') !== false ||
            stripos($title, 'primary') === 0 ||
            stripos($title, 'homepage') === 0 ||
            stripos($title, 'header') === 0 ||
            stripos($title, 'footer') === 0 ||
            preg_match('/\.(jpg|jpeg|png|gif|webp)$/i', $title) ||
            strpos($content, '{"version"') === 0
            // if ($post['title'] === "Software Projects")
        ) {
            continue;
        }

        // Replace image paths
        $content = str_replace(
            [
                'https://sarahrose843696274.files.wordpress.com/',
                'https://sarahrosehassan.com/wp-content/uploads/',
            ],
            '/media/',
            $content
        );
        
        // Extract first image from content
        preg_match('/<img[^>]+src=["\']([^"\']+)["\']/i', $content, $matches);
        $thumbnail = $matches[1] ?? null;
        
        $posts[] = [
            'title' => $title,
            'date' => $date,
            'content' => $content,
            'thumbnail' => $thumbnail
        ];

    }

    // Sort by date descending
    usort($posts, function ($a, $b) {
        return strtotime($b['date']) - strtotime($a['date']);
    });

    if ($limit) {
        $posts = array_slice($posts, 0, $limit);
    }

    return $posts;
}
?>
